name: Build

on:
  push:
    branches:
      - "master"

jobs:
  build_app:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - run: go build cmd/app/main.go
